<!DOCTYPE html>
<html lang="en">

<head>
    <style>
    .slick-slide {
        margin: 0 15px;
        /* jarak kiri-kanan antar logo */
    }

    .slick-slide img {
        display: inline-block;
        width: 150px;
        /* pastikan ukuran konsisten */
        height: auto;
        margin: 0 auto;
    }

    .slick-list {
        margin: 0 -15px;
        /* kompensasi margin supaya slider tetap sejajar */
    }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Preload Images -->
    <link rel="preload" as="image" href="<?= base_url('assets/landing/assets/logo/logo.png')?>" />
    <link rel="preload" as="image" href="<?= base_url('assets/landing/assets/footer/logo.svg')?>" />

    <!-- Stylesheet -->
    <link rel="stylesheet" href="<?= base_url('assets/landing/_next/static/css/90b998279a8ebee8.css') ?>"
        data-precedence="next" />

    <!-- Scripts -->
    <link rel="preload" as="script" fetchPriority="low"
        href="<?= base_url('assets/landing/_next/static/chunks/webpack-d420d104885f077b.js') ?>" />
    <script src="<?= base_url('assets/landing/_next/static/chunks/fd9d1056-3408cbf259188e8c.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/117-8d9effb19d35c063.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/main-app-3a02c3db59818438.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/233-7eec004fbee1878b.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/406-28ed49a20a679aa0.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/app/page-407e552224e697dd.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/237-cc7dbec964db8d0b.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/app/layout-bb30ef3a7869a03d.js') ?>" async>
    </script>
    <!-- Meta -->
    <title>Tabungan-Karya</title>
    <meta name="description" content="Generated by create next app" />

    <!-- Favicons -->
    <link rel="icon" href="<?= base_url('assets/landing/favicon.ico') ?>" type="image/x-icon" sizes="16x16" />
    <link rel="icon" href="<?= base_url('assets/landing/icon.ico') ?>" type="image/x-icon" sizes="32x29" />

    <!-- Polyfills -->
    <script src="<?= base_url('assets/landing/_next/static/chunks/polyfills-42372ed130431b0a.js') ?>" noModule></script>

    <link rel="stylesheet" type="text/css" href="<?= base_url('node_modules/slick/slick.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= base_url('node_modules/slick/slick-theme.css') ?>" />

</head>


<body>
    <nav class="navbar" data-headlessui-state="">
        <div class="mx-auto max-w-7xl px-6 lg:py-4 lg:px-8">
            <div class="relative flex h-20 items-center justify-between">
                <div class="flex flex-1 items-center sm:items-stretch sm:justify-start">
                    <div class="flex flex-shrink-0 items-center"><img class="block h-12 w-40 lg:hidden"
                            src="<?= base_url('assets/landing/assets/logo/logo.png')?>" alt="dsign-logo" /><img
                            class="hidden h-full w-full lg:block"
                            src="<?= base_url('assets/landing/assets/logo/logo.png')?>" alt="dsign-logo" />
                    </div>
                    <div class="hidden lg:block m-auto">
                        <div class="flex space-x-4"><a
                                class=" text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="<?=base_url()?>">Home</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#services">Services</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#about">About</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#project">Project</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="<?=base_url()?>">Help</a></div>
                    </div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center sm:static sm:inset-auto sm:pr-0">
                    <div class="hidden lg:block"><button type="button" class="text-lg text-blue font-medium">Sign
                            In</button></div>
                </div>
                <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto  sm:pr-0">
                    <div class="hidden lg:block"><button
                            class="text-blue text-lg font-medium ml-9 py-5 px-16 transition duration-150 ease-in-out leafbutton bg-lightblue hover:text-white hover:bg-blue">Sign
                            up</button></div>
                </div>
                <div class="block lg:hidden"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon"
                        class="block h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
                    </svg></div>
                <main
                    class=" fixed overflow-hidden z-10 bg-gray-900 bg-opacity-25 inset-0 transform ease-in-out  transition-all delay-500 opacity-0 -translate-x-full  ">
                    <section
                        class="w-340px max-w-lg left-0 absolute bg-white h-full shadow-xl delay-400 duration-500 ease-in-out transition-all transform -translate-x-full">
                        <article class="relative w-270 max-w-lg pb-10 flex flex-col space-y-6 h-full">
                            <header class="p-4 flex items-center justify-between"><img class="h-12 w-40"
                                    src="<?= base_url('assets/landing/assets/logo/logo.png')?>"
                                    alt="Courses-Logo" /><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true"
                                    data-slot="icon" class="block h-6 w-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12">
                                    </path>
                                </svg></header>
                            <div>
                                <div class="rounded-md max-w-sm w-full mx-auto">
                                    <div class="flex-1 space-y-4 py-1">
                                        <div class="sm:block">
                                            <div class="space-y-1 px-5 pt-2 pb-3"><a
                                                    class="text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    aria-current="page" href="<?=base_url()?>">Home</a><a
                                                    class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#services">Services</a><a
                                                    class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#about">About</a><a
                                                    class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#project">Project</a><a
                                                    class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="<?=base_url()?>">Help</a>
                                                <div class="mt-4"></div><button
                                                    class="bg-white w-full text-blue border border-lightblue font-medium py-2 px-4 rounded">Sign
                                                    In</button><button
                                                    class="bg-lightblue w-full hover:bg-blue hover:text-white text-blue font-medium my-2 py-2 px-4 rounded">Sign
                                                    up</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </section>
                    <section class=" w-screen h-full cursor-pointer "></section>
                </main>
            </div>
        </div>
    </nav>
    <main>
        <main>
            <div class="px-6 lg:px-8">
                <div class="mx-auto max-w-7xl pt-16 sm:pt-20 pb-20 banner-image">
                    <div class="text-center">
                        <h1 class="text-4xl font-semibold text-navyblue sm:text-5xl lg:text-7xl md:4px lh-96">
                            Tabungan Karya, <br> Ruang Digital Guru Berinovasi.
                        </h1>
                        <p class="mt-6 text-lg leading-8 text-bluegray">
                            Platform untuk mendokumentasikan, menampilkan, dan menginspirasi lewat karya pendidikan.
                        </p>

                    </div>
                    <div class="text-center mt-5">
                    </div><img alt="banner-image" loading="lazy" width="1200" height="598" decoding="async"
                        data-nimg="1" style="color:transparent"
                        src="<?= base_url('assets/landing/assets/banner/dashboard.jpeg')?>" />
                </div>
            </div>
        </main>
        <div class="text-center">
            <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
                <div class="py-14">
                    <div class="slick-slider">
                        <img src="<?= base_url('assets/landing/assets/carousel/google.svg') ?>" alt="Google" />
                        <img src="<?= base_url('assets/landing/assets/carousel/garnier.png') ?>" alt="Garnier" />
                        <img src="<?= base_url('assets/landing/assets/carousel/slack.png') ?>" alt="Slack" />
                        <img src="<?= base_url('assets/landing/assets/carousel/udemy.png') ?>" alt="Udemy" />
                        <img src="<?= base_url('assets/landing/assets/carousel/google.svg') ?>" alt="Google" />
                        <img src="<?= base_url('assets/landing/assets/carousel/garnier.png') ?>" alt="Garnier" />
                        <img src="<?= base_url('assets/landing/assets/carousel/slack.png') ?>" alt="Slack" />
                        <img src="<?= base_url('assets/landing/assets/carousel/udemy.png') ?>" alt="Udemy" />
                        <img src="<?= base_url('assets/landing/assets/carousel/google.svg') ?>" alt="Google" />
                        <img src="<?= base_url('assets/landing/assets/carousel/garnier.png') ?>" alt="Garnier" />
                        <img src="<?= base_url('assets/landing/assets/carousel/slack.png') ?>" alt="Slack" />
                        <img src="<?= base_url('assets/landing/assets/carousel/udemy.png') ?>" alt="Udemy" />
                    </div>
                </div>
                <hr />
            </div>
        </div>

        <div class="mx-auto max-w-7xl py-16 px-6">
            <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-y-20 gap-x-5">
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/ourbuyers.svg')?>" loading="lazy" width="30"
                            height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/ourbuyers.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5">80k
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Our buyers
                    </h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Follow a hashtag growth
                        total posts, videos and images.</p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/projectcompleted.svg')?>" loading="lazy"
                            width="30" height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/projectcompleted.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5">90k
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Project
                        completed</h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Follow a hashtag growth
                        total posts, videos and images.</p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/happybuyers.svg')?>" loading="lazy"
                            width="30" height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/happybuyers.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5">80%
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Happy buyers
                    </h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Follow a hashtag growth
                        total posts, videos and images.</p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/teammembers.svg')?>" loading="lazy"
                            width="30" height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/teammembers.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5">50+
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Team members
                    </h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Follow a hashtag growth
                        total posts, videos and images.</p>
                </div>
            </div>
        </div>
        <div id="services">
            <div class="mx-auto max-w-7xl px-4 my-10 sm:py-20 lg:px-8">
                <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
                    <div class="col-span-6 flex justify-center">
                        <div class="flex flex-col align-middle justify-center p-10">
                            <p class="text-4xl lg:text-6xl pt-4 font-semibold lh-81 mt-5 text-center lg:text-start">
                                We
                                provide that service.</p>
                            <h4 class="text-lg pt-4 font-normal lh-33 text-center lg:text-start text-bluegray">
                                Sed ut
                                perspiciatis unde omnis iste natus error sit voluptatem accusantium
                                doloremque
                                laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                                veritatis et quasi
                                architecto beatae vitae dicta sunt explicabo</h4><a
                                class="mt-4 text-xl font-medium text-blue flex gap-2 mx-auto lg:mx-0 space-links"
                                href="<?=base_url()?>>">Learn more
                                <!-- --> <img alt="arrow" loading="lazy" width="20" height="20" decoding="async"
                                    data-nimg="1" style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/provide/arrow.svg')?>" />
                            </a>
                        </div>
                    </div>
                    <div class="lg:col-span-1"></div>
                    <div class="col-span-6 lg:col-span-5">
                        <div
                            class="grid grid-cols-1 sm:grid-cols-2 gap-x-16 gap-y-10 lg:gap-x-40 px-10 py-12 bg-bluebg rounded-3xl">
                            <div class="bg-white rounded-3xl lg:-ml-32 p-6 shadow-xl"><img
                                    alt="<?= base_url('assets/landing/assets/provide/marketing.svg')?>" loading="lazy"
                                    width="64" height="64" decoding="async" data-nimg="1" class="mb-5"
                                    style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/provide/marketing.svg')?>" />
                                <h4 class="text-2xl font-semibold">Marketing</h4>
                                <h4 class="text-lg font-normal text-bluegray my-2">Follow a hashtag
                                    total posts, videos
                                </h4>
                            </div>
                            <div class="bg-white rounded-3xl lg:-ml-32 p-6 shadow-xl"><img
                                    alt="<?= base_url('assets/landing/assets/provide/graphic.svg')?>" loading="lazy"
                                    width="64" height="64" decoding="async" data-nimg="1" class="mb-5"
                                    style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/provide/graphic.svg')?>" />
                                <h4 class="text-2xl font-semibold">Graphic design</h4>
                                <h4 class="text-lg font-normal text-bluegray my-2">Follow a hashtag
                                    total posts, videos
                                </h4>
                            </div>
                            <div class="bg-white rounded-3xl lg:-ml-32 p-6 shadow-xl"><img
                                    alt="<?= base_url('assets/landing/assets/provide/heaking.svg')?>" loading="lazy"
                                    width="64" height="64" decoding="async" data-nimg="1" class="mb-5"
                                    style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/provide/heaking.svg')?>" />
                                <h4 class="text-2xl font-semibold">Heaking</h4>
                                <h4 class="text-lg font-normal text-bluegray my-2">Follow a hashtag
                                    total posts, videos
                                </h4>
                            </div>
                            <div class="bg-white rounded-3xl lg:-ml-32 p-6 shadow-xl"><img
                                    alt="<?= base_url('assets/landing/assets/provide/uidesign.svg')?>" loading="lazy"
                                    width="64" height="64" decoding="async" data-nimg="1" class="mb-5"
                                    style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/provide/uidesign.svg')?>" />
                                <h4 class="text-2xl font-semibold">UI/UX Design</h4>
                                <h4 class="text-lg font-normal text-bluegray my-2">Follow a hashtag
                                    total posts, videos
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="about">
            <div class="mx-auto max-w-7xl px-4 my-20 sm:py-20 lg:px-8">
                <div class="grid grid-cols-1 lg:grid-cols-2">
                    <div class="lg:-ml-64"><img alt="iPad-image" loading="lazy" width="4000" height="900"
                            decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/why/iPad.png')?>" />
                    </div>
                    <div>
                        <h3
                            class="text-4xl lg:text-5xl pt-4 font-semibold sm:leading-tight mt-5 text-center lg:text-start">
                            Why we best?</h3>
                        <h4 class="text-lg pt-4 font-normal sm:leading-tight text-center text-beach lg:text-start">Dont
                            waste time on search manual tasks. Let Automation do it for you. Simplify workflows, reduce
                            errors, and save time.</h4>
                        <div class="mt-10">
                            <div class="flex mt-4">
                                <div class="rounded-full h-10 w-12 flex items-center justify-center bg-circlebg"><img
                                        alt="check-image" loading="lazy" width="24" height="24" decoding="async"
                                        data-nimg="1" style="color:transparent"
                                        src="<?= base_url('assets/landing/assets/why/check.svg')?>" />
                                </div>
                                <div class="ml-5">
                                    <h4 class="text-2xl font-semibold">Quality</h4>
                                    <h5 class="text-lg text-beach font-normal mt-2">Follow a hashtag growth
                                        total posts,
                                        videos and images.more revitions</h5>
                                </div>
                            </div>
                            <div class="flex mt-4">
                                <div class="rounded-full h-10 w-12 flex items-center justify-center bg-circlebg">
                                    <img alt="check-image" loading="lazy" width="24" height="24" decoding="async"
                                        data-nimg="1" style="color:transparent"
                                        src="<?= base_url('assets/landing/assets/why/check.svg')?>" />
                                </div>
                                <div class="ml-5">
                                    <h4 class="text-2xl font-semibold">Communication</h4>
                                    <h5 class="text-lg text-beach font-normal mt-2">Follow a hashtag growth
                                        total posts,
                                        videos and images.more revitions</h5>
                                </div>
                            </div>
                            <div class="flex mt-4">
                                <div class="rounded-full h-10 w-12 flex items-center justify-center bg-circlebg">
                                    <img alt="check-image" loading="lazy" width="24" height="24" decoding="async"
                                        data-nimg="1" style="color:transparent"
                                        src="<?= base_url('assets/landing/assets/why/check.svg')?>" />
                                </div>
                                <div class="ml-5">
                                    <h4 class="text-2xl font-semibold">Reliability</h4>
                                    <h5 class="text-lg text-beach font-normal mt-2">Follow a hashtag growth
                                        total posts,
                                        videos and images.more revitions</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-babyblue" id="project">
            <div class="mx-auto max-w-2xl py-20 px-4 sm:px-6 lg:max-w-7xl lg:px-8">
                <h3 class="text-4xl sm:text-6xl font-semibold text-center my-10 lh-81">Our network &amp; world
                    <br />
                    work details.
                </h3><img alt="map-image" loading="lazy" width="1400" height="800" decoding="async" data-nimg="1"
                    style="color:transparent" src="<?= base_url('assets/landing/assets/network/map.png')?>" />
                <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-x-16 gap-y-4 lg:gap-x-8">
                    <div class="bg-white rounded-2xl p-5 shadow-xl">
                        <div class="flex justify-start items-center gap-2"><img
                                alt="<?= base_url('assets/landing/assets/network/bangladesh.svg')?>" loading="lazy"
                                width="55" height="55" decoding="async" data-nimg="1" class="mb-2"
                                style="color:transparent"
                                src="<?= base_url('assets/landing/assets/network/bangladesh.svg')?>" />
                            <h4 class="text-xl font-medium text-midnightblue">Bangladesh</h4>
                        </div>
                        <hr />
                        <h4 class="text-lg font-normal text-bluegrey my-2">Event madness gathering innoies, &amp; tech
                            enthusiasts in Speced.</h4>
                    </div>
                    <div class="bg-white rounded-2xl p-5 shadow-xl">
                        <div class="flex justify-start items-center gap-2"><img
                                alt="<?= base_url('assets/landing/assets/network/america.svg')?>" loading="lazy"
                                width="55" height="55" decoding="async" data-nimg="1" class="mb-2"
                                style="color:transparent"
                                src="<?= base_url('assets/landing/assets/network/america.svg')?>" />
                            <h4 class="text-xl font-medium text-midnightblue">United States</h4>
                        </div>
                        <hr />
                        <h4 class="text-lg font-normal text-bluegrey my-2">Event madness gathering innoies, &amp; tech
                            enthusiasts in Speced.</h4>
                    </div>
                    <div class="bg-white rounded-2xl p-5 shadow-xl">
                        <div class="flex justify-start items-center gap-2"><img
                                alt="<?= base_url('assets/landing/assets/network/australia.svg')?>" loading="lazy"
                                width="55" height="55" decoding="async" data-nimg="1" class="mb-2"
                                style="color:transparent"
                                src="<?= base_url('assets/landing/assets/network/australia.svg')?>" />
                            <h4 class="text-xl font-medium text-midnightblue">Australia</h4>
                        </div>
                        <hr />
                        <h4 class="text-lg font-normal text-bluegrey my-2">Event madness gathering innoies, &amp; tech
                            enthusiasts in Speced.</h4>
                    </div>
                    <div class="bg-white rounded-2xl p-5 shadow-xl">
                        <div class="flex justify-start items-center gap-2"><img
                                alt="<?= base_url('assets/landing/assets/network/china.svg')?>" loading="lazy"
                                width="55" height="55" decoding="async" data-nimg="1" class="mb-2"
                                style="color:transparent"
                                src="<?= base_url('assets/landing/assets/network/china.svg')?>" />
                            <h4 class="text-xl font-medium text-midnightblue">China</h4>
                        </div>
                        <hr />
                        <h4 class="text-lg font-normal text-bluegrey my-2">Event madness gathering innoies, &amp; tech
                            enthusiasts in Speced.</h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="mx-auto max-w-2xl py-40 px-4s sm:px-6 lg:max-w-7xl lg:px-8">
            <div class="bg-image-what">
                <h3 class="text-navyblue text-center text-4xl lg:text-6xl font-semibold">What say clients about us.</h3>
                <h4 class="text-lg font-normal text-darkgray text-center mt-4">Event madness gathering innoies,&amp;
                    tech enthusiasts in Speced. <br /> <!-- -->do more informations.</h4>
                <div class="lg:relative"><img alt="avatar-image" loading="lazy" width="1061" height="733"
                        decoding="async" data-nimg="1" class="hidden lg:block" style="color:transparent"
                        src="<?= base_url('assets/landing/assets/clientsay/avatars.png')?>" /><span
                        class="lg:absolute lg:bottom-40 lg:left-80"><img alt="user-image" loading="lazy" width="168"
                            height="168" decoding="async" data-nimg="1" class="mx-auto pt-10 lg:pb-10"
                            style="color:transparent"
                            src="<?= base_url('assets/landing/assets/clientsay/user.png')?>" />
                        <div class="lg:inline-block bg-white rounded-2xl p-5 shadow-sm">
                            <p class="text-base font-normal text-center text-darkgray">Build your financial literacy
                                within a transparent <br /> <!-- -->community. Follow other investors, share people from
                                <br /> <!-- -->different professional backgrounds, and never be alone.
                            </p>
                            <h3 class="text-2xl font-medium text-center py-2">Jony Scotty</h3>
                            <h4 class="text-sm font-normal text-center">UI Designer</h4>
                        </div>
                    </span></div>
            </div>
        </div>
        <div class="-mt-32 relative z-3">
            <div class="mx-auto max-w-2xl lg:max-w-7xl bg-blue-500 rounded-3xl">
                <div class="grid grid-cols-1 gap-y-10 gap-x-6 lg:grid-cols-2 xl:gap-x-8">
                    <div class="hidden lg:block">
                        <div class="float-right pt-20 relative"><img alt="bgimg" loading="lazy" width="588" height="334"
                                decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/newsletter/bgImage.png')?>" />
                            <div class="absolute top-10 right-0"><img alt="leafimg" loading="lazy" width="81"
                                    height="81" decoding="async" data-nimg="1" style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/newsletter/leaf.svg')?>" />
                            </div>
                            <div class="absolute bottom-8 left-2"><img alt="circleimg" loading="lazy" width="30"
                                    height="30" decoding="async" data-nimg="1" style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/newsletter/circel.svg')?>" />
                            </div>
                        </div>
                    </div>
                    <div class="p-10 flex flex-col justify-center">
                        <h3 class="text-4xl md:text-5xl font-semibold mb-3 text-white">Sign up to our newsletter.</h3>
                        <h4 class="text-base font-normal mb-7 text-offwhite">Craven omni memoria patriae zombieland
                            clairvius narcisse religionis sunt diri undead historiarum.</h4>
                        <div class="flex gap-0"><input type="Email address"
                                class="py-4 text-sm w-full text-black bg-white rounded-l-lg pl-4"
                                placeholder="@enter email-address" autoComplete="off" name="q" /><button
                                class="bg-midblue text-white font-medium py-2 px-4 rounded-r-lg"><img alt="plane-img"
                                    loading="lazy" width="20" height="20" decoding="async" data-nimg="1"
                                    style="color:transparent"
                                    src="<?= base_url('assets/landing/assets/newsletter/plane.svg')?>" /></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <div class="bg-darkblue -mt-40">
        <div class="mx-auto max-w-2xl pt-48 px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <div class="my-24 grid grid-cols-1 gap-y-10 gap-x-16 sm:grid-cols-2 lg:grid-cols-12 xl:gap-x-8">
                <div class="col-span-4 md:col-span-12 lg:col-span-4"><img
                        src="<?= base_url('assets/landing/assets/footer/logo.svg')?>" alt="logo" class="pb-8" />
                    <div class="flex gap-4"><a class="footer-fb-icons" href="#!"><img alt="facebook" loading="lazy"
                                width="15" height="20" decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/facebook.svg')?>" /></a><a
                            class="footer-icons" href="#!"><img alt="twitter" loading="lazy" width="20" height="20"
                                decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/twitter.svg')?>" /></a><a
                            class="footer-icons" href="#!"><img alt="instagram" loading="lazy" width="20" height="20"
                                decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/instagram.svg')?>" /></a>
                    </div>
                </div>
                <div class="group relative col-span-2 md:col-span-4 lg:col-span-2">
                    <ul>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Home</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Popular</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">About</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Contact</a></li>
                    </ul>
                </div>
                <div class="group relative col-span-2 md:col-span-4 lg:col-span-2">
                    <ul>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Help</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Resources</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Application</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Team</a></li>
                    </ul>
                </div>
                <div class="col-span-4 md:col-span-4 lg:col-span-4">
                    <div class="flex gap-2"><img alt="mask-icon" loading="lazy" width="24" height="24" decoding="async"
                            data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/footer/mask.svg')?>" />
                        <h5 class="text-base font-normal text-offwhite">925 Filbert Street Pennsylvania 18072</h5>
                    </div>
                    <div class="flex gap-2 mt-10"><img alt="telephone-icon" loading="lazy" width="24" height="24"
                            decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/footer/telephone.svg')?>" />
                        <h5 class="text-base font-normal text-offwhite">+ 45 34 11 44 11</h5>
                    </div>
                    <div class="flex gap-2 mt-10"><img alt="email-icon" loading="lazy" width="24" height="24"
                            decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/footer/email.svg')?>" />
                        <h5 class="text-base font-normal text-offwhite">info@gmail.com</h5>
                    </div>
                </div>
            </div>
            <div class="py-10 lg:flex items-center justify-between border-t border-t-bordertop">
                <h4 class="text-offwhite text-sm text-center lg:text-start font-normal">@2025 Agency. All Rights
                    Reserved by
                    <!-- --> <a target="_blank" href="https://getnextjstemplates.com/">
                        <!-- -->GetNextjsTemplates.
                    </a> <!-- -->Distributed by
                    <!-- --> <a target="_blank" href="https://themewagon.com/">ThemeWagon</a>
                </h4>
                <div class="flex gap-5 mt-5 lg:mt-0 justify-center lg:justify-start">
                    <h4 class="text-offwhite text-sm font-normal"><a href="#!" class="cursor-pointer">Privacy policy</a>
                    </h4>
                    <div class="h-5 bg-bordertop w-0.5"></div>
                    <h4 class="text-offwhite text-sm font-normal"><a href="#!" class="cursor-pointer">Terms &amp;
                            conditions</a></h4>
                </div>
            </div>
        </div>
    </div>
    <!-- Next.js Runtime -->

    <!-- Core JS -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/main-9bb8076eb397129e.js') ?>"></script>

    <!-- Page & App -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/pages/_app-72b849fbd24ac258.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/406-28ed49a20a679aa0.js') ?>"></script>

    <!-- Misc -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/117-8d9effb19d35c063.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/233-7eec004fbee1878b.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/237-cc7dbec964db8d0b.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/fd9d1056-3408cbf259188e8c.js') ?>">
    </script>

    <!-- Error handler (optional) -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/pages/_error-7ba65e1336b92748.js') ?>"></script>
    <!-- sebelum </body> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="<?= base_url('node_modules/slick/slick.min.js') ?>"></script>


</body>
<script>
document.addEventListener('DOMContentLoaded', () => {
    updateScrollState();
    window.addEventListener('scroll', updateScrollState);
});

function updateScrollState() {
    document.documentElement.setAttribute('data-scroll', scrollY);
}

const menuBtn = document.querySelector('.block.lg\\:hidden svg');
const mobileMenu = document.querySelector('nav main');

menuBtn.addEventListener('click', () => {
    mobileMenu.classList.toggle('opacity-0');
    mobileMenu.classList.toggle('-translate-x-full');
    mobileMenu.classList.toggle('opacity-100');
    mobileMenu.classList.toggle('translate-x-0');
});
$(document).ready(function() {
    $('.slick-slider').slick({
        slidesToShow: 4,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 2000,
        arrows: false,
        dots: false,
        infinite: true,
        centerMode: false,
        pauseOnHover: false
    });
});
</script>

</html>