<!DOCTYPE html>
<html lang="en">

<head>
    <style>
    /* Jika Anda memiliki lebih dari satu section yang perlu diperbaiki */
    #services,
    #about,
    #project {
        scroll-margin-top: 500px;
    }

    .slick-slide {
        margin: 0 15px;
        /* jarak kiri-kanan antar logo */
    }

    .slick-slide img {
        display: inline-block;
        width: 150px;
        /* pastikan ukuran konsisten */
        height: auto;
        margin: 0 auto;
    }

    .slick-list {
        margin: 0 -15px;
        /* kompensasi margin supaya slider tetap sejajar */
    }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Preload Images -->
    <!-- <link rel="preload" as="image" href="<?= base_url('assets/landing/assets/logo/logo.png')?>" />
    <link rel="preload" as="image" href="<?= base_url('assets/landing/assets/footer/logo.svg')?>" /> -->

    <!-- Stylesheet -->
    <link rel="stylesheet" href="<?= base_url('assets/landing/_next/static/css/90b998279a8ebee8.css') ?>"
        data-precedence="next" />

    <!-- Scripts -->
    <link rel="preload" as="script" fetchPriority="low"
        href="<?= base_url('assets/landing/_next/static/chunks/webpack-d420d104885f077b.js') ?>" />
    <script src="<?= base_url('assets/landing/_next/static/chunks/fd9d1056-3408cbf259188e8c.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/117-8d9effb19d35c063.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/main-app-3a02c3db59818438.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/233-7eec004fbee1878b.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/406-28ed49a20a679aa0.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/app/page-407e552224e697dd.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/237-cc7dbec964db8d0b.js') ?>" async>
    </script>
    <script src="<?= base_url('assets/landing/_next/static/chunks/app/layout-bb30ef3a7869a03d.js') ?>" async>
    </script>
    <!-- Meta -->
    <title>Tabungan-Karya</title>
    <meta name="description" content="Generated by create next app" />

    <!-- Favicons -->
    <!-- <link rel="icon" href="<?= base_url('assets/landing/favicon.ico') ?>" type="image/x-icon" sizes="16x16" />
    <link rel="icon" href="<?= base_url('assets/landing/icon.ico') ?>" type="image/x-icon" sizes="32x29" /> -->

    <!-- Polyfills -->
    <script src="<?= base_url('assets/landing/_next/static/chunks/polyfills-42372ed130431b0a.js') ?>" noModule></script>

    <link rel="stylesheet" type="text/css" href="<?= base_url('node_modules/slick/slick.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?= base_url('node_modules/slick/slick-theme.css') ?>" />

</head>


<body>
    <nav class="navbar" data-headlessui-state="">
        <div class="mx-auto max-w-7xl px-6 lg:py-4 lg:px-8">
            <div class="relative flex h-20 items-center justify-between">
                <div class="flex flex-1 items-center sm:items-stretch sm:justify-start">
                    <div class="hidden lg:block m-auto">
                        <div id="desktop-menu" class="flex space-x-4"><a
                                class=" text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#home">Home</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#karya">Karya</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#statistik">Data Statistik</a><a
                                class="hover:text-black hover:opacity-100 px-3 py-4 text-lg font-normal opacity-75 space-links"
                                aria-current="page" href="#contacts">Hubungi Kami</a></div>
                    </div>
                </div>
                <div class="relative inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:pr-0">
                    <?php if (!empty($this->session->userdata('nama'))): ?>
                    <div class="hidden lg:flex items-center space-x-3 ml-9">
                        <a href="<?= base_url('home/dashboard') ?>"
                            class="text-blue text-lg font-medium ml-9 py-5 px-16 transition duration-150 ease-in-out leafbutton bg-lightblue hover:text-white hover:bg-blue">
                            Dashboard
                        </a>
                        <a href="<?= base_url('auth/logout') ?>"
                            class="text-sm font-medium px-4 py-2 rounded-lg bg-red-500 text-white hover:bg-red-600 transition duration-150 ease-in-out">
                            <i class="fas fa-sign-out-alt mr-2"></i> Logout
                        </a>
                    </div>
                    <?php else: ?>
                    <div class="hidden lg:block">
                        <a href="<?= base_url("auth/login") ?>"
                            class="text-blue text-lg font-medium ml-9 py-5 px-16 transition duration-150 ease-in-out leafbutton bg-lightblue hover:text-white hover:bg-blue">
                            Masuk
                        </a>
                    </div>
                    <?php endif; ?>
                </div>

                <div id="menu-toggle" class="block lg:hidden cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" data-slot="icon" class="block h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5">
                        </path>
                    </svg>
                </div>
                <!-- Menu mobile -->
                <main id="mobile-nav"
                    class="fixed inset-0 z-40 hidden overflow-hidden bg-gray-900 bg-opacity-25 transform transition-all duration-300 ease-in-out opacity-0">
                    <section id="menu-overlay" class="absolute inset-0 w-screen h-full cursor-pointer z-40"></section>
                    <section id="mobile-panel"
                        class="absolute left-0 top-0 h-full w-72 ... bg-white shadow-xl transition-transform duration-300 ease-in-out z-50">
                        <article class="relative w-270 max-w-lg pb-10 flex flex-col space-y-6 h-full">
                            <header class="p-4 flex items-center justify-between">
                                <button id="menu-close" class="text-gray-700">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon"
                                        class="block h-6 w-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12">
                                        </path>
                                    </svg>
                                </button>
                            </header>
                            <div>
                                <div class="rounded-md max-w-sm w-full mx-auto">
                                    <div class="flex-1 space-y-4 py-1">
                                        <div class="sm:block">
                                            <div class="space-y-1 px-5 pt-2 pb-3">
                                                <a class="text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    aria-current="page" href="<?=base_url()?>">Home</a>
                                                <a class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#karya">Karya</a>
                                                <a class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#statistik">Data Statistik</a>
                                                <a class="hover:text-black hover:opacity-100 px-2 py-1 text-lg font-normal opacity-75 block"
                                                    href="#contacts">Hubungi Kami</a>
                                                <div class="mt-4">

                                                </div>
                                                <?php if (!empty($this->session->userdata('nama'))): ?>
                                                <div class="flex flex-col space-y-3 mt-5">
                                                    <a href="<?= base_url('home/dashboard') ?>"
                                                        class="block w-full text-center text-blue text-lg font-semibold py-3 rounded-xl transition duration-150 ease-in-out bg-lightblue hover:bg-blue hover:text-white">
                                                        Dashboard
                                                    </a>
                                                    <a href="<?= base_url('auth/logout') ?>"
                                                        class="block w-full text-center text-white text-base font-medium py-3 rounded-xl bg-red-500 hover:bg-red-600 transition duration-150 ease-in-out">
                                                        <i class="fas fa-sign-out-alt mr-2"></i> Logout
                                                    </a>
                                                </div>
                                                <?php else: ?>
                                                <div class="flex flex-col mt-5">
                                                    <a href="<?= base_url('auth/login') ?>"
                                                        class="block w-full text-center text-blue text-lg font-semibold py-3 rounded-xl transition duration-150 ease-in-out bg-lightblue hover:bg-blue hover:text-white">
                                                        Masuk
                                                    </a>
                                                </div>
                                                <?php endif; ?>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    </section>

                </main>
            </div>
        </div>
    </nav>
    <main>
        <main>
            <div id="home" class="px-6 lg:px-8">
                <div class="mx-auto max-w-7xl pt-16 sm:pt-20 pb-20 banner-image">
                    <div class="text-center">
                        <h1 class="text-4xl font-semibold text-navyblue sm:text-5xl lg:text-7xl md:4px lh-96">
                            Tabungan Karya, <br> Ruang Digital Guru Berinovasi.
                        </h1>
                        <p class="mt-6 text-lg leading-8 text-bluegray">
                            Platform digital untuk mendokumentasikan, mengelola, dan menampilkan
                            karya para guru dalam satu sistem terpadu. <br> Melalui website ini, guru dapat mengunggah
                            karya
                            inovatif, berbagi inspirasi, serta membangun portofolio profesional yang berkelanjutan.
                        </p>
                    </div>
                    <div class="text-center mt-10">
                        <p class="text-lg font-medium text-navyblue">
                            Ide dan Konsep Dicetuskan oleh
                        </p>
                        <p class="text-2xl font-bold text-navyblue mb-4">
                            Kepala Sekolah
                        </p>
                    </div>
                    <img alt="banner-image" loading="lazy" decoding="async"
                        class="mx-auto mt-10 w-full max-w-lg lg:max-w-lg"
                        src="<?= base_url('assets/landing/assets/banner/dashboard.JPG')?>" />
                </div>
            </div>
        </main>
        <div id="karya" style="scroll-margin-top: 150px;" class="text-center **py-20**">
            <hr class="mb-12 border-gray-300">
            <br>
            <div class="mx-auto **max-w-4xl** px-4 sm:px-6 lg:px-8">
                <h2 class="text-3xl font-semibold text-gray-800 **mb-16**">
                    Jenis Karya yang Dapat Diunggah
                </h2>
                <br>
                <div class="slick-slider-types">

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-blue-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-blue-300">
                        <i class="fas fa-video text-blue-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Video</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-red-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-red-300">
                        <i class="fas fa-book-open text-red-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Novel</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-green-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-green-300">
                        <i class="fas fa-feather-alt text-green-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Puisi</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-yellow-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-yellow-300">
                        <i class="fas fa-pencil-alt text-yellow-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Cerpen</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-purple-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-purple-300">
                        <i class="fas fa-palette text-purple-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Poster</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-indigo-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-indigo-300">
                        <i class="fas fa-newspaper text-indigo-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Artikel</h3>

                    </div>

                    <div
                        class="**p-10** bg-white rounded-3xl shadow-2xl border-2 border-pink-100 mx-4 transition duration-300 hover:shadow-3xl hover:border-pink-300">
                        <i class="fas fa-book text-pink-600 **text-7xl** mb-6 block"></i>
                        <h3 class="text-3xl font-extrabold text-gray-900 mb-2">Jurnal</h3>
                    </div>

                </div>

            </div>
            <br>
            <hr class="mt-12 border-gray-300">
        </div>
        <div id="statistik" class="mx-auto max-w-7xl py-16 px-6">
            <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-y-20 gap-x-5">
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/ourbuyers.svg')?>" loading="lazy" width="30"
                            height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/ourbuyers.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5"><?= $total_guru ?>
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Total Guru
                    </h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Jumlah guru yang telah bergabung pada Tabungan-Karya</p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/projectcompleted.svg')?>" loading="lazy"
                            width="30" height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/projectcompleted.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5"><?= $total_karya ?>
                    </h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">
                        Total Karya</h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Jumlah karya yang telah terdata</p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <div class="flex justify-center border border-border  p-2 w-10 rounded-lg"><img
                            alt="<?= base_url('assets/landing/assets/buyers/happybuyers.svg')?>" loading="lazy"
                            width="30" height="30" decoding="async" data-nimg="1" style="color:transparent"
                            src="<?= base_url('assets/landing/assets/buyers/happybuyers.svg')?>" />
                    </div>
                    <h2 class="text-4xl lg:text-6xl text-black font-semibold text-center mt-5">
                        <?= $guru_terbanyak ? $guru_terbanyak->nama : '-' ?></h2>
                    <h3 class="text-2xl text-black font-semibold text-center lg:mt-6">Guru Terproduktif
                    </h3>
                    <p class="text-lg font-normal text-black text-center text-opacity-50 mt-2">
                        Telah menghasilkan karya terbanyak</p>
                </div>
            </div>
        </div>
    </main>
    <div id="contacts" class="bg-darkblue">
        <div class="mx-auto max-w-2xl pt-10 px-4 sm:px-6 lg:max-w-7xl lg:px-8">
            <div class="my-24 grid grid-cols-1 gap-y-10 gap-x-16 sm:grid-cols-2 lg:grid-cols-12 xl:gap-x-8">
                <div class="col-span-4 md:col-span-12 lg:col-span-4">
                    <!-- <img src="<?= base_url('assets/landing/assets/footer/logo.svg')?>" alt="logo" class="pb-8" /> -->
                    <div class="flex gap-4"><a class="footer-fb-icons" href="#!"><img alt="facebook" loading="lazy"
                                width="15" height="20" decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/facebook.svg')?>" /></a><a
                            class="footer-icons" href="#!"><img alt="twitter" loading="lazy" width="20" height="20"
                                decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/twitter.svg')?>" /></a><a
                            class="footer-icons" href="#!"><img alt="instagram" loading="lazy" width="20" height="20"
                                decoding="async" data-nimg="1" style="color:transparent"
                                src="<?= base_url('assets/landing/assets/footer/instagram.svg')?>" /></a>
                    </div>
                </div>
                <div class="group relative col-span-2 md:col-span-4 lg:col-span-2">
                    <ul>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Home</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Popular</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">About</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Contact</a></li>
                    </ul>
                </div>
                <div class="group relative col-span-2 md:col-span-4 lg:col-span-2">
                    <ul>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Help</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Resources</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Application</a></li>
                        <li class="mb-5"><a class="text-white text-sm font-normal mb-6 space-links"
                                href="<?=base_url()?>">Team</a></li>
                    </ul>
                </div>

            </div>
            <div class="py-10 lg:flex items-center justify-between border-t border-t-bordertop">

            </div>
        </div>
    </div>
    <!-- Next.js Runtime -->

    <!-- Core JS -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/main-9bb8076eb397129e.js') ?>"></script>

    <!-- Page & App -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/pages/_app-72b849fbd24ac258.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/406-28ed49a20a679aa0.js') ?>"></script>

    <!-- Misc -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/117-8d9effb19d35c063.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/233-7eec004fbee1878b.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/237-cc7dbec964db8d0b.js') ?>"></script>
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/fd9d1056-3408cbf259188e8c.js') ?>">
    </script>

    <!-- Error handler (optional) -->
    <script defer src="<?= base_url('assets/landing/_next/static/chunks/pages/_error-7ba65e1336b92748.js') ?>"></script>
    <!-- sebelum </body> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="<?= base_url('node_modules/slick/slick.min.js') ?>"></script>


</body>
<script>
document.addEventListener('DOMContentLoaded', () => {
    updateScrollState();
    window.addEventListener('scroll', updateScrollState);

    const menuToggle = document.getElementById("menu-toggle");
    const mobileNav = document.getElementById("mobile-nav");
    const mobilePanel = document.getElementById("mobile-panel");
    const menuClose = document.getElementById("menu-close");
    const menuOverlay = document.getElementById("menu-overlay");

    // Fungsi untuk buka menu
    function openMenu() {
        console.log("Menu dibuka");
        mobileNav.classList.remove("hidden");
        setTimeout(() => {
            mobileNav.classList.remove("opacity-0");
            mobilePanel.classList.remove("-translate-x-full");
        }, 10);
    }

    // Fungsi untuk tutup menu
    function closeMenu() {
        console.log("Menu ditutup");
        mobileNav.classList.add("opacity-0");
        mobilePanel.classList.add("-translate-x-full");
        setTimeout(() => {
            mobileNav.classList.add("hidden");
        }, 300);
    }

    // Klik hamburger → buka menu
    menuToggle.addEventListener("click", () => {
        console.log("Klik hamburger icon");
        openMenu();
    });

    // Klik tombol close → tutup menu
    menuClose.addEventListener("click", () => {
        console.log("Klik tombol close (X)");
        closeMenu();
    });

    // Klik overlay → tutup menu
    menuOverlay.addEventListener("click", () => {
        console.log("Klik overlay di luar panel");
        closeMenu();
    });

    // Debug semua klik di dalam panel
    mobilePanel.addEventListener("click", (e) => {
        const target = e.target.closest("a, button");
        if (target) {
            console.log("Klik elemen di panel:", target.tagName, target.textContent.trim(), "→", target
                .getAttribute("href"));
        } else {
            console.log("Klik area kosong di panel drawer");
        }
    });

    // Tangani klik pada link
    const links = mobilePanel.querySelectorAll("a");
    links.forEach(link => {
        link.addEventListener("click", (e) => {
            const href = link.getAttribute("href");
            console.log("Klik link:", href);

            // Jika link ke anchor (#bagian)
            if (href && href.startsWith("#")) {
                console.log("Navigasi internal ke:", href);
                closeMenu();
                return;
            }

            // Jika ke halaman lain
            e.preventDefault();
            closeMenu();
            console.log("Menunggu animasi sebelum pindah halaman:", href);
            setTimeout(() => {
                window.location.href = href;
            }, 200);
        });
    });

    $('.slick-slider-types').slick({
        slidesToShow: 6,
        slidesToScroll: 1,
        autoplay: true,
        autoplaySpeed: 1,
        speed: 5000,
        cssEase: 'linear',
        arrows: false,
        dots: false,
        infinite: true,
        centerMode: false,
        pauseOnHover: false,

        responsive: [{
                breakpoint: 1024, // tablet
                settings: {
                    slidesToShow: 6
                }
            },
            {
                breakpoint: 768, // hp landscape
                settings: {
                    slidesToShow: 5
                }
            },
            {
                breakpoint: 480, // hp kecil
                settings: {
                    slidesToShow: 3
                }
            }
        ]
    });
});

function updateScrollState() {
    document.documentElement.setAttribute('data-scroll', scrollY);
}


function toggleDropdown() {
    // Mendapatkan elemen dropdown berdasarkan ID
    const dropdown = document.getElementById('user-dropdown');

    // Toggle (menghapus/menambahkan) kelas 'hidden'
    dropdown.classList.toggle('hidden');
}

// PENTING: Menutup dropdown saat mengklik di luar menu
document.addEventListener('click', function(event) {
    const dropdown = document.getElementById('user-dropdown');
    const button = document.getElementById('dropdownButton');

    // Jika klik bukan pada tombol DAN dropdown sedang terbuka
    if (dropdown && button && !dropdown.contains(event.target) && !button.contains(event.target) && !dropdown
        .classList.contains('hidden')) {
        dropdown.classList.add('hidden');
    }
});
</script>

</html>